/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as InstagramRouteImport } from './routes/instagram'
import { Route as HelicopterRouteImport } from './routes/helicopter'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as EmptyLegsRouteImport } from './routes/empty-legs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BespokeRouteImport } from './routes/bespoke'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoutesSlugRouteImport } from './routes/routes.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const InstagramRoute = InstagramRouteImport.update({
  id: '/instagram',
  path: '/instagram',
  getParentRoute: () => rootRouteImport,
} as any)
const HelicopterRoute = HelicopterRouteImport.update({
  id: '/helicopter',
  path: '/helicopter',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const EmptyLegsRoute = EmptyLegsRouteImport.update({
  id: '/empty-legs',
  path: '/empty-legs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BespokeRoute = BespokeRouteImport.update({
  id: '/bespoke',
  path: '/bespoke',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesSlugRoute = RoutesSlugRouteImport.update({
  id: '/routes/$slug',
  path: '/routes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bespoke': typeof BespokeRoute
  '/contact': typeof ContactRoute
  '/empty-legs': typeof EmptyLegsRoute
  '/fleet': typeof FleetRoute
  '/helicopter': typeof HelicopterRoute
  '/instagram': typeof InstagramRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/routes/$slug': typeof RoutesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bespoke': typeof BespokeRoute
  '/contact': typeof ContactRoute
  '/empty-legs': typeof EmptyLegsRoute
  '/fleet': typeof FleetRoute
  '/helicopter': typeof HelicopterRoute
  '/instagram': typeof InstagramRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/routes/$slug': typeof RoutesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bespoke': typeof BespokeRoute
  '/contact': typeof ContactRoute
  '/empty-legs': typeof EmptyLegsRoute
  '/fleet': typeof FleetRoute
  '/helicopter': typeof HelicopterRoute
  '/instagram': typeof InstagramRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/routes/$slug': typeof RoutesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bespoke'
    | '/contact'
    | '/empty-legs'
    | '/fleet'
    | '/helicopter'
    | '/instagram'
    | '/pricing'
    | '/sitemap.xml'
    | '/routes/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bespoke'
    | '/contact'
    | '/empty-legs'
    | '/fleet'
    | '/helicopter'
    | '/instagram'
    | '/pricing'
    | '/sitemap.xml'
    | '/routes/$slug'
  id:
    | '__root__'
    | '/'
    | '/bespoke'
    | '/contact'
    | '/empty-legs'
    | '/fleet'
    | '/helicopter'
    | '/instagram'
    | '/pricing'
    | '/sitemap.xml'
    | '/routes/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BespokeRoute: typeof BespokeRoute
  ContactRoute: typeof ContactRoute
  EmptyLegsRoute: typeof EmptyLegsRoute
  FleetRoute: typeof FleetRoute
  HelicopterRoute: typeof HelicopterRoute
  InstagramRoute: typeof InstagramRoute
  PricingRoute: typeof PricingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  RoutesSlugRoute: typeof RoutesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instagram': {
      id: '/instagram'
      path: '/instagram'
      fullPath: '/instagram'
      preLoaderRoute: typeof InstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/helicopter': {
      id: '/helicopter'
      path: '/helicopter'
      fullPath: '/helicopter'
      preLoaderRoute: typeof HelicopterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empty-legs': {
      id: '/empty-legs'
      path: '/empty-legs'
      fullPath: '/empty-legs'
      preLoaderRoute: typeof EmptyLegsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bespoke': {
      id: '/bespoke'
      path: '/bespoke'
      fullPath: '/bespoke'
      preLoaderRoute: typeof BespokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/$slug': {
      id: '/routes/$slug'
      path: '/routes/$slug'
      fullPath: '/routes/$slug'
      preLoaderRoute: typeof RoutesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BespokeRoute: BespokeRoute,
  ContactRoute: ContactRoute,
  EmptyLegsRoute: EmptyLegsRoute,
  FleetRoute: FleetRoute,
  HelicopterRoute: HelicopterRoute,
  InstagramRoute: InstagramRoute,
  PricingRoute: PricingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  RoutesSlugRoute: RoutesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
