/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HelicopterRouteImport } from './routes/helicopter'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as EmptyLegsRouteImport } from './routes/empty-legs'
import { Route as BespokeRouteImport } from './routes/bespoke'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoutesSlugRouteImport } from './routes/routes.$slug'

const HelicopterRoute = HelicopterRouteImport.update({
  id: '/helicopter',
  path: '/helicopter',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const EmptyLegsRoute = EmptyLegsRouteImport.update({
  id: '/empty-legs',
  path: '/empty-legs',
  getParentRoute: () => rootRouteImport,
} as any)
const BespokeRoute = BespokeRouteImport.update({
  id: '/bespoke',
  path: '/bespoke',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesSlugRoute = RoutesSlugRouteImport.update({
  id: '/routes/$slug',
  path: '/routes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bespoke': typeof BespokeRoute
  '/empty-legs': typeof EmptyLegsRoute
  '/fleet': typeof FleetRoute
  '/helicopter': typeof HelicopterRoute
  '/routes/$slug': typeof RoutesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bespoke': typeof BespokeRoute
  '/empty-legs': typeof EmptyLegsRoute
  '/fleet': typeof FleetRoute
  '/helicopter': typeof HelicopterRoute
  '/routes/$slug': typeof RoutesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bespoke': typeof BespokeRoute
  '/empty-legs': typeof EmptyLegsRoute
  '/fleet': typeof FleetRoute
  '/helicopter': typeof HelicopterRoute
  '/routes/$slug': typeof RoutesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bespoke'
    | '/empty-legs'
    | '/fleet'
    | '/helicopter'
    | '/routes/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bespoke'
    | '/empty-legs'
    | '/fleet'
    | '/helicopter'
    | '/routes/$slug'
  id:
    | '__root__'
    | '/'
    | '/bespoke'
    | '/empty-legs'
    | '/fleet'
    | '/helicopter'
    | '/routes/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BespokeRoute: typeof BespokeRoute
  EmptyLegsRoute: typeof EmptyLegsRoute
  FleetRoute: typeof FleetRoute
  HelicopterRoute: typeof HelicopterRoute
  RoutesSlugRoute: typeof RoutesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/helicopter': {
      id: '/helicopter'
      path: '/helicopter'
      fullPath: '/helicopter'
      preLoaderRoute: typeof HelicopterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empty-legs': {
      id: '/empty-legs'
      path: '/empty-legs'
      fullPath: '/empty-legs'
      preLoaderRoute: typeof EmptyLegsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bespoke': {
      id: '/bespoke'
      path: '/bespoke'
      fullPath: '/bespoke'
      preLoaderRoute: typeof BespokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/$slug': {
      id: '/routes/$slug'
      path: '/routes/$slug'
      fullPath: '/routes/$slug'
      preLoaderRoute: typeof RoutesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BespokeRoute: BespokeRoute,
  EmptyLegsRoute: EmptyLegsRoute,
  FleetRoute: FleetRoute,
  HelicopterRoute: HelicopterRoute,
  RoutesSlugRoute: RoutesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
